name: personal_expenses_app_by_gj
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  charts_flutter: ^0.12.0
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.12
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+1
  mobx_codegen: ^2.1.1
  flutter_riverpod: ^2.2.0
  uuid: ^3.0.7
  jiffy: ^5.0.0
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
          weight: 400                    
        - asset: fonts/NotoSans-Italic.ttf      
          weight: 400               
          style: italic
        - asset: fonts/NotoSans-Light.ttf
          weight: 300                
        - asset: fonts/NotoSans-LightItalic.ttf
          weight: 300                
          style: italic        
        - asset: fonts/NotoSans-ExtraLight.ttf
          weight: 200                        
        - asset: fonts/NotoSans-ExtraLightItalic.ttf        
          weight: 200                        
          style: italic        
        - asset: fonts/NotoSans-Black.ttf
          weight: 900            
        - asset: fonts/NotoSans-BlackItalic.ttf
          weight: 900            
          style: italic        
        - asset: fonts/NotoSans-Thin.ttf
          weight: 100        
        - asset: fonts/NotoSans-ThinItalic.ttf             
          weight: 100                
          style: italic        
        - asset: fonts/NotoSans-Medium.ttf
          weight: 500                        
        - asset: fonts/NotoSans-MediumItalic.ttf                     
          weight: 500                        
          style: italic        
        - asset: fonts/NotoSans-SemiBold.ttf
          weight: 600                
        - asset: fonts/NotoSans-SemiBoldItalic.ttf                             
          weight: 600                
          style: italic        
        - asset: fonts/NotoSans-Bold.ttf
          weight: 700                 
        - asset: fonts/NotoSans-BoldItalic.ttf                             
          weight: 700                 
          style: italic        
        - asset: fonts/NotoSans-ExtraBold.ttf
          weight: 800                 
        - asset: fonts/NotoSans-ExtraBoldItalic.ttf                                             
          weight: 800                 
          style: italic        

